config/routes.rb
BookmarkZone::Application.routes.draw do  

  resources :users
  resources :books
  resources :marks
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/about',   :to => 'pages#about'
  match '/books',   :to => 'books#index'

  match '/signup',   :to => 'users#new'
  
  match '/addbook',   :to => 'books#new'
  match '/removebook',   :to => 'books#destroy'

  root :to => 'pages#home'

end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :book
  has_attached_file :image, :styles => { :large => "600x450>", :medium => "300x300>", :thumb => "100x100>" }
  # in order for this to work you must have imagemagick installed
  # brew install imagemagick
  attr_accessible :page, :note, :image
  
  validates :page, :presence => true,
                    :length => { :maximum => 10 }
  
  validates :note, :presence => true
  
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  def new
  end
  
  def create
    book_id = params[:mark][:book_id]
    current_book = Book.find(book_id)
    @mark = current_book.marks.new(:page => params[:mark][:page],
                        :note => params[:mark][:note])
    if @mark.save
      flash.now[:success] = "Mark Created!"
      redirect_to current_book
    else
      flash.now[:error] = "Mark could not be created."
      @title = "Add mark"
      redirect_to current_book
      #this is a BUG it should render current_book showing the mark errs
    end
  end
  
  def edit
    @mark = Mark.find(params[:id])
    @title = "Edit mark"
  end
  
  def update
    @mark = Mark.find(params[:id])
    if @mark.update_attributes(params[:mark])
      flash[:success] = "Mark updated."
      redirect_to @mark
    else
      @title = "Edit mark"
      render 'edit'
    end
  end
  
  def show
    @mark = Mark.find(params[:id])
    @title = "Page #{@mark.page}"
  end
  
  def destroy
    Mark.find(params[:id]).destroy
    flash[:success] = "Mark Deleted."
    redirect_to book_path
  end
end

app/helpers/marks_helper.rb
module MarksHelper
  
  def current_book
    @current_book = Book.find(@mark.book_id)
  end
  
end

app/views/marks/_addmark.html.erb
<p>
	<h2>
		Add more marks
	</h2>
	
	<%= form_for @mark do |f| %>
	
	<%= render 'shared/error_messages', :object => f.object %>
	
	
	  <div class="field">
		<%= f.label :page %><br />
		<%= f.text_field :page %>
	  </div>

	  <div class="field">
	    <%= f.label :note %><br />
	    <%= f.text_area :note, :cols => "1", :rows => "1" %>
	  </div>
	
	  <div class="field">
	    <%= f.label :image %><br />
	    <%= f.file_field :image %>
	  </div>

	  <div class="actions">
		<%= f.hidden_field:book_id, :value => @book.id %>
	    <%= f.submit "Add mark" %>
	  </div>

	<% end %>
</p>

app/views/marks/edit.html.erb
<h1>Edit mark</h1>

<%= form_for @mark, :html => { :multipart => true } do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :page %><br />
    <%= f.text_field :page %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/marks/new.html.erb
<h1>Marks#new</h1>
<p>Find me in app/views/marks/new.html.erb</p>

app/views/marks/show.html.erb
<h1>Page <%= @mark.page %></h1>

<p><%= @mark.note %></p>

<p>
	<%= image_tag @mark.image.url(:large) %>
</p>

<p>
	<%= link_to "Edit mark", edit_mark_path(@mark) %> 
	|
	<%= link_to "Back to book", current_book %>
</p>