config/routes.rb
BookmarkZone::Application.routes.draw do  

  resources :users
  resources :books
  resources :marks
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/about',   :to => 'pages#about'
  match '/books',   :to => 'books#index'

  match '/signup',   :to => 'users#new'
  
  match '/addbook',   :to => 'books#new'
  match '/removebook',   :to => 'books#destroy'

  root :to => 'pages#home'

end

app/views/pages/about.html.erb
<h1>About Bookmark Zone</h1>
<p>Bookmark zone is a glorious place where you can save the bookmarks to all your favorite books. Once we go public, our shares will be common stock. In 7 years percisely, our users (which we don't have yet) will be able to purchase stock. And while it is worth nothing now, years from now, perhaps, it will be worth something. The founding equity will cascade as new founders are included.</p>

app/views/pages/home.html.erb
<% if signed_in? %>
	<h1>
	  Welcome <%= @user.name %>
	</h1>

	<p>
		You have <%= pluralize(@user.books.count, 'book') %>. <br>
	</p>

	<p>
		<% @user.books.each do |b| %>
			<br><i><%= link_to b.name, b %></i><br>
		<% end %>
	</p>
	
	</section><br>
	<section class="round">
	<%= render 'books/addbook' %>
	
	<p>
		<%= link_to "Edit user", edit_user_path(@user) %>
	</p>
	
<% else %>
	<p>Welcome to Bookmarkzone. Here you can bookmark things. Pretty sweet, huh?</p>

	<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
<% end %>