config/routes.rb
BookmarkZone::Application.routes.draw do  

  resources :users
  resources :books
  resources :marks
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/about',   :to => 'pages#about'
  match '/books',   :to => 'books#index'

  match '/signup',   :to => 'users#new'
  
  match '/addbook',   :to => 'books#new'
  match '/removebook',   :to => 'books#destroy'

  root :to => 'pages#home'

end

app/models/book.rb
class Book < ActiveRecord::Base
  require 'open-uri'
  require 'json'
  
  belongs_to :user
  has_many :marks
  attr_accessible :title, :author
  
  
  validates :title, :presence => true,
                    :length => { :maximum => 50 },
                    :uniqueness => { :case_sensitive => false }
  
  validates :author, :presence => true,
                     :length => { :maximum => 50 }
                    
  def name
    "#{title} by #{author}"
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @title = "Add book"
    @book = Book.new
  end
  
  def index
    @title = "All Books"
    @books = Book.all
  end
  
  def create
    @book = current_user.books.new(:title => params[:book][:title],
                        :author => params[:book][:author])
    if @book.save
      flash.now[:success] = "Book Created!"
      redirect_to @book
    else
      flash.now[:error] = "Book could not be created."
      @title = "Add book"
      render 'new'
    end
  end
  
  def edit
    @book = Book.find(params[:id])
    @title = "Edit book"
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(params[:book])
      flash[:success] = "Book updated."
      redirect_to @book
    else
      @title = "Edit book"
      render 'edit'
    end
  end
  
  def show
    @book = Book.find(params[:id])
    @title = @book.title
    @mark = Mark.new
    @user = User.find(@book.user_id)
    @user_is_book_owner = (@user == current_user)
  end
  
  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "Book Deleted."
    redirect_to book_path
  end

end

app/helpers/books_helper.rb
module BooksHelper
  
  def userIsBookOwner?(currentUser)
    User.find(@book.user_id) == currentUser
  end
  
  def good_reads_widget
    require 'open-uri'

    begin

    	bookuri = 'http://www.goodreads.com/book/title?format=json&author=' + @book.author + '&title=' + @book.title + '&key=LNsDBhLQTvWd1JSdLIUXQ'
    	j = open bookuri.tr(' ','+')

    	string = j.string

    	allReviews = ActiveSupport::JSON.decode(string)
    	allReviewsCode = allReviews["reviews_widget"]

    rescue Exception=>e
    	allReviewsCode = "Could not Good Reads"
    end
    
    return allReviewsCode
  end
    
end

app/views/books/_addbook.html.erb
<p>
	<h2>
		Add more books
	</h2>
	
	<%= form_for@book do |f| %>
	
	<%= render 'shared/error_messages', :object => f.object %>
	
	  <div class="field">
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	  </div>

	  <div class="field">
	    <%= f.label :author %><br />
	    <%= f.text_field :author %>
	  </div>

	  <div class="actions">
	    <%= f.submit "Add book" %>
	  </div>

	<% end %>
</p>

app/views/books/edit.html.erb
<h1>Edit book</h1>

<%= form_for(@book) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/books/index.html.erb
<h1>All books</h1>

<ul>
  <% @books.each do |b| %>
    <li>
      <%= link_to b.name, b %>
    </li>
  <% end %>
</ul>

app/views/books/new.html.erb
<h1>Create Book</h1>

<%= render 'addbook' %>

app/views/books/show.html.erb
<h1><u>
	<%= @book.name %>
</u></h1>

<p>
	This book has <%= pluralize(@book.marks.count, "bookmark") %>.
</p>


<p>
	<% @book.marks.each do |m| %>
		<br><i><%= link_to m.page, m %></i>  - <%= m.note %><br>
	<% end %>
</p>

<p>
	<% if can_access?(@book) %>
	<%= link_to "Edit book", edit_book_path(@book) %> 
	| 
	<% end %>
	<%= link_to "Back to my Profile", root_path %>
</p>

<% if userIsBookOwner?(current_user) %>

	</section>
	<section class="round">
	<%= render 'marks/addmark' %>

<% end %>

</section>
<section class="round">

<%=  raw good_reads_widget %>