config/routes.rb
BookmarkZone::Application.routes.draw do  

  resources :users
  resources :books
  resources :marks
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/about',   :to => 'pages#about'
  match '/books',   :to => 'books#index'

  match '/signup',   :to => 'users#new'
  
  match '/addbook',   :to => 'books#new'
  match '/removebook',   :to => 'books#destroy'

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
      		<li><%= link_to "Books", books_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
      		<li><%= link_to "Books", books_path %></li>
			<% if signed_in? %>
			<li><%= link_to "Profile", current_user %></li>
			<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
			<% else %>
			<li><%= link_to "Sign in", signin_path %></li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    "application" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag :defaults %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
	<% flash.each do |key, value| %>
		<div class="flash <%= key %>"><%= value %></div>
	<% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>